
server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: postgres://wxgqpnwkcmqhgg:5f531a2504250f4c3b012dc986793787e6de7bfe5fd45a5ed58db7099884edd9@ec2-54-158-232-223.compute-1.amazonaws.com:5432/da88atd2msfs8d
    username: wxgqpnwkcmqhgg
    password: 5f531a2504250f4c3b012dc986793787e6de7bfe5fd45a5ed58db7099884edd9
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      hibernate:
        ddl-auto: none

application:
  description: Projeto criado para o Bootcamp Dio - Santander / Backend
